version: "3.9"

services:
  web:
    build: .
    ports:
      - "80:80"
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
