version: "3.9"

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    environment:
      - NODE_ENV=production
